import java.awt.*;
import java.io.*;
import java.nio.file.*;
import java.sql.*;
import javax.swing.*;

import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.awt.Desktop;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author New
 */


public class BookInfoPage extends javax.swing.JFrame {
     String rootpath="C:\\Users\\New\\Documents\\NetBeansProjects\\Digital_Library\\src\\DigitalLibraryResources\\CoverPhotos\\";
 String rootpath1="C:\\Users\\New\\Documents\\NetBeansProjects\\Digital_Library\\src\\DigitalLibraryResources\\";
 String rootpath2="C:\\Users\\New\\Documents\\NetBeansProjects\\Digital_Library\\src\\";

     public static int flag=0;
public static String username="";
 String bookname="", authorname="",bookcategory="",bookcoverphoto="",bookpdf="1.pdf"; 
    /**
     * Creates new form BookInfoPage
     */
    public BookInfoPage() {
          
       
        initComponents();
         displaybookinfo();
            
             ImageIcon img=new ImageIcon( rootpath2+"logout.png");
            //           Resize Image to filt jLabel
            Image image=img.getImage().getScaledInstance(jLabel9.getWidth(),jLabel9.getHeight(),Image.SCALE_SMOOTH);
            jLabel9.setIcon(new ImageIcon(image));
          ProfileName2.setText(username);
         setExtendedState(JFrame.MAXIMIZED_BOTH);   
    }

    public void displaybookinfo(){
               try {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/digitallibrary?"
            +"user=root&password=suraj123");
            PreparedStatement stmt=conn.prepareStatement("select * from digitallibrary.bookinfo where id=?");
            stmt.setInt(1, flag);
           
                ResultSet rs=stmt.executeQuery();
                while(rs.next()){
                    bookname=rs.getString(2);
                    authorname=rs.getString(3);
                    bookcategory=rs.getString(4);
                    bookcoverphoto=rs.getString(5);
                    bookpdf=rs.getString(6);
//                    rs.next();        //index contains id also
        }
              jLabel2.setText(bookname);
              jLabel6.setText(bookname);
              jLabel7.setText(authorname);
              jLabel8.setText(bookcategory);
               //Display image on jlabel
            ImageIcon img=new ImageIcon(rootpath+bookcoverphoto);

            //           Resize Image to filt jLabel
            Image image=img.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(image));
                
             
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Title = new javax.swing.JPanel();
        TitleName = new javax.swing.JLabel();
        ProfileBar = new javax.swing.JPanel();
        ProfileName1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ProfileName2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Info Page");
        setBackground(new java.awt.Color(204, 218, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(102, 102, 102));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(102, 102, 102));
        Title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleName.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        TitleName.setForeground(new java.awt.Color(255, 255, 255));
        TitleName.setText("Digital Library");
        Title.add(TitleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 338, 77));

        Header.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 6, 351, 89));

        ProfileBar.setBackground(new java.awt.Color(102, 102, 102));
        ProfileBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProfileName1.setBackground(new java.awt.Color(102, 102, 102));
        ProfileName1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ProfileName1.setForeground(new java.awt.Color(255, 255, 255));
        ProfileName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileName1.setText("USER");
        ProfileBar.add(ProfileName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 220, -1));

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        ProfileBar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 50, 20));

        ProfileName2.setBackground(new java.awt.Color(102, 102, 102));
        ProfileName2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ProfileName2.setForeground(new java.awt.Color(255, 255, 255));
        ProfileName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileName2.setText("USER");
        ProfileBar.add(ProfileName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, -1));

        Header.add(ProfileBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 320, 60));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 83));

        jPanel1.setBackground(new java.awt.Color(204, 182, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 210, 240));

        jButton4.setBackground(new java.awt.Color(51, 102, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Download");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jButton5.setBackground(new java.awt.Color(51, 102, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 400, 420));

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name of the Book");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Book Name : ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Author Name : ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Category :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel6.setText("Book");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel7.setText("Author");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel8.setText("Category");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 520, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 1020, 470));

        Footer.setBackground(new java.awt.Color(102, 255, 255));
        Footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 102, 255));
        jLabel50.setText("Copyright All rights Reserverd. Designed & Developed by S. S. Upadhye.");
        Footer.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 560, 30));

        getContentPane().add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1390, 60));

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Desktop.getDesktop().open(new java.io.File(rootpath1+bookpdf));
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "The File is not Available");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String sourceFilePath = rootpath1+bookpdf; 
    String destinationDirectory = System.getProperty("user.home") + File.separator + "Downloads";

    Path sourcePath = Paths.get(sourceFilePath);
    Path destinationPath = Paths.get(destinationDirectory, sourcePath.getFileName().toString());

    if (Files.exists(destinationPath)) {
        int count = 1;
        String fileName = sourcePath.getFileName().toString();
        String baseName = fileName.substring(0, fileName.lastIndexOf('.'));
        String extension = fileName.substring(fileName.lastIndexOf('.'));
        do {
            destinationPath = Paths.get(destinationDirectory, baseName + "_" + count + extension);
            count++;
        } while (Files.exists(destinationPath));
    }

    try {
        Files.copy(sourcePath, destinationPath);
        JOptionPane.showMessageDialog(null, "File downloaded successfully to " + destinationPath.toString());
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "The file could not be downloaded.");
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    String filePath = rootpath1+bookpdf; // Replace this with the actual file path
    try {
        Process process = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + filePath);
        process.waitFor();
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
        String line;
        StringBuilder output = new StringBuilder();
        while ((line = reader.readLine()) != null) {
            output.append(line).append("\n");
        }
        JOptionPane.showMessageDialog(null, "File printed successfully.");
    } catch (IOException | InterruptedException e) {
        JOptionPane.showMessageDialog(null, "An error occurred while printing: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
        dispose();
        HomePage HP=new HomePage();
        HP.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
        JOptionPane.showMessageDialog(null, "Logout Successful..!!");
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookInfoPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel ProfileBar;
    private javax.swing.JLabel ProfileName1;
    private javax.swing.JLabel ProfileName2;
    private javax.swing.JPanel Title;
    private javax.swing.JLabel TitleName;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
